export const user = [
  {
    firstName: 'mukesha',
    lastName: 'agime',
    email: 'mentee@gmail.com',
    password: 'dfghjk',
    address: 'kigali',
    bio: 'iaminnocent',
    occupation: 'nurse',
    expertise: 'doctor',
    type: 'mentee',
  },
  {
    firstName: 'mukesha',
    lastName: 'yves',
    email: 'admin@gmail.com',
    password: 'uwimanaRT54',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'swdeveloper',
    expertise: 'master',
  },
  {
    id: 3,
    firstName: 'new',
    lastName: 'yves',
    email: 'new@gmail.com',
    password: 'uwimana3',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'sw-developer',
    expertise: 'master',
    type: 'mentor',
  },
  {
    firstName: 'mukesha',
    lastName: 'agime',
    email: 'new@gmail.com',
    password: 'dfghjkTY23',
    address: 'kigali',
    bio: 'iaminnocent',
    occupation: 'nurse',
    expertise: 'doctor',
  },
];

export const login = {
  email: 'admin@gmail.com',
  password: 'admin',
};
