const users = [
  {

    id: 1,
    firstName: 'mukesha',
    lastName: 'agime',
    email: 'mentee@gmail.com',
    password: '$2b$10$UQvtPGglSGUBX3gjH8il3uWHV5IOv8bHp0hK8toDo4aForTkQHMFa',
    address: 'kigali',
    bio: 'i am innocent',
    occupation: 'nurse',
    expertise: 'doctor',
    type: 'mentee',
  },
  {
    id: 2,
    firstName: 'uwimana',
    lastName: 'yves',
    email: 'admin@gmail.com',
    password: '$2b$10$jlT.LKKqgQNGLXBOfd78I.dK5g3BMmsgK4ajP7aYY/6An0mQuh.Re',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'sw-developer',
    expertise: 'master',
    type: 'admin',
  },
  {
    id: 3,
    firstName: 'uwimana3',
    lastName: 'yves',
    email: 'mentor@gmail.com',
    password: '$2b$10$tc.3crtDhoA78TrL26p7ZOWq9A/o3J31KOD4zA74Fu8wlh7uN1TNS',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'sw-developer',
    expertise: 'master',
    type: 'mentor',
  },
  {
    token: '',
    id: 4,
    firstName: 'uwimana4',
    lastName: 'yves',
    email: 'yves4@gmail.com',
    password: 'uwimana4',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'sw-developer',
    expertise: 'master',
    type: 'mentee',
  },
  {
    token: '',
    id: 5,
    firstName: 'uwimana456',
    lastName: 'yves',
    email: 'kamanzi123@gmail.com',
    password: 'uwimana',
    address: 'kayonza',
    bio: 'hhhhhhh',
    occupation: 'sw-developer',
    expertise: 'master',
    type: 'mentor',
  },
];

export default users;
